version: '3.4'

networks:
  services-network:
    driver: bridge

services:
  servicetwo:
    container_name: servicetwo
    image: servicetwo:latest
    depends_on:
      - db
    build:
      context: servicetwo
      dockerfile: Dockerfile
    networks:
      - services-network
  db:
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password3"
      ACCEPT_EULA: "Y"
    networks:
      - services-network
    volumes:
      - ./Init:/docker-entrypoint-initdb.d
    image: "mcr.microsoft.com/mssql/server:2022-latest"