version: '3.4'

networks:
  services-network:
    driver: bridge

services:
  servicetwo:
    container_name: servicetwo
    image: servicetwo:latest
    depends_on:
      - "db"
    build:
      dockerfile: Dockerfile
      context: servicetwo
    ports:
      - "5050:80"
    networks:
      - services-network
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password3"
      ACCEPT_EULA: "Y"
    networks:
      - services-network
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
      - ./init.sql:/docker-entrypoint-initdb.d